/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Thu Dec 27 20:46:17 EST 2018
 * 
 */
#ifndef __vpi_wrapper_c_putchar_h__
#define __vpi_wrapper_c_putchar_h__

#include <vpi_user.h>

/* registration function */
void c_putchar_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_putchar_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_putchar_h__ */
