/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Wed Nov 14 14:45:15 EST 2018
 * 
 */
#ifndef __vpi_wrapper_c_trygetchar_h__
#define __vpi_wrapper_c_trygetchar_h__

#include <vpi_user.h>

/* registration function */
void c_trygetchar_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_trygetchar_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_trygetchar_h__ */
