/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Fri Dec 21 11:00:53 EST 2018
 * 
 */
#ifndef __vpi_wrapper_c_get_symbol_val_h__
#define __vpi_wrapper_c_get_symbol_val_h__

#include <vpi_user.h>

/* registration function */
void c_get_symbol_val_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_get_symbol_val_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_get_symbol_val_h__ */
