###  -*-Makefile-*-

# Copyright (c) 2018 Bluespec, Inc. All Rights Reserved

# ================================================================

include ../Resources/Include_RV32ACDFIMSU.mk

include ../Resources/Include_verilator.mk

# ================================================================
