//
// Generated by Bluespec Compiler, version 2017.07.A (build 5e200f8fc, 2017-07-21)
//
// On Fri Jan 18 13:36:40 EST 2019
//
//
// Ports:
// Name                         I/O  size props
// RDY_cpu_reset_server_request_put  O     1 reg
// RDY_cpu_reset_server_response_get  O     1 reg
// cpu_imem_master_awvalid        O     1
// cpu_imem_master_awaddr         O    64 reg
// cpu_imem_master_awprot         O     3 reg
// cpu_imem_master_wvalid         O     1
// cpu_imem_master_wdata          O    64 reg
// cpu_imem_master_wstrb          O     8 reg
// cpu_imem_master_bready         O     1
// cpu_imem_master_arvalid        O     1
// cpu_imem_master_araddr         O    64 reg
// cpu_imem_master_arprot         O     3 reg
// cpu_imem_master_rready         O     1
// cpu_dmem_master_awvalid        O     1
// cpu_dmem_master_awaddr         O    64 reg
// cpu_dmem_master_awprot         O     3 reg
// cpu_dmem_master_wvalid         O     1
// cpu_dmem_master_wdata          O    64 reg
// cpu_dmem_master_wstrb          O     8 reg
// cpu_dmem_master_bready         O     1
// cpu_dmem_master_arvalid        O     1
// cpu_dmem_master_araddr         O    64 reg
// cpu_dmem_master_arprot         O     3 reg
// cpu_dmem_master_rready         O     1
// cpu_slave_awready              O     1 const
// cpu_slave_wready               O     1 const
// cpu_slave_bvalid               O     1 const
// cpu_slave_bresp                O     2 const
// cpu_slave_arready              O     1 const
// cpu_slave_rvalid               O     1 const
// cpu_slave_rresp                O     2 const
// cpu_slave_rdata                O    64 const
// RDY_set_verbosity              O     1 const
// RDY_dm_dmi_read_addr           O     1
// dm_dmi_read_data               O    32
// RDY_dm_dmi_read_data           O     1
// RDY_dm_dmi_write               O     1
// RDY_dm_ndm_reset_req_get_get   O     1 reg
// dm_master_awvalid              O     1
// dm_master_awaddr               O    64 reg
// dm_master_awprot               O     3 reg
// dm_master_wvalid               O     1
// dm_master_wdata                O    64 reg
// dm_master_wstrb                O     8 reg
// dm_master_bready               O     1 const
// dm_master_arvalid              O     1
// dm_master_araddr               O    64 reg
// dm_master_arprot               O     3 reg
// dm_master_rready               O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// cpu_imem_master_awready        I     1
// cpu_imem_master_wready         I     1
// cpu_imem_master_bvalid         I     1
// cpu_imem_master_bresp          I     2 reg
// cpu_imem_master_arready        I     1
// cpu_imem_master_rvalid         I     1
// cpu_imem_master_rresp          I     2 reg
// cpu_imem_master_rdata          I    64 reg
// cpu_dmem_master_awready        I     1
// cpu_dmem_master_wready         I     1
// cpu_dmem_master_bvalid         I     1
// cpu_dmem_master_bresp          I     2 reg
// cpu_dmem_master_arready        I     1
// cpu_dmem_master_rvalid         I     1
// cpu_dmem_master_rresp          I     2 reg
// cpu_dmem_master_rdata          I    64 reg
// cpu_slave_awvalid              I     1 unused
// cpu_slave_awaddr               I    64 unused
// cpu_slave_awprot               I     3 unused
// cpu_slave_wvalid               I     1 unused
// cpu_slave_wdata                I    64 unused
// cpu_slave_wstrb                I     8 unused
// cpu_slave_bready               I     1 unused
// cpu_slave_arvalid              I     1 unused
// cpu_slave_araddr               I    64 unused
// cpu_slave_arprot               I     3 unused
// cpu_slave_rready               I     1 unused
// cpu_external_interrupt_req_set_not_clear  I     1 reg
// set_verbosity_verbosity        I     4
// set_verbosity_logdelay         I    64 reg
// dm_dmi_read_addr_dm_addr       I     7
// dm_dmi_write_dm_addr           I     7
// dm_dmi_write_dm_word           I    32
// dm_master_awready              I     1
// dm_master_wready               I     1
// dm_master_bvalid               I     1
// dm_master_bresp                I     2 reg
// dm_master_arready              I     1
// dm_master_rvalid               I     1
// dm_master_rresp                I     2 reg
// dm_master_rdata                I    64 reg
// EN_cpu_reset_server_request_put  I     1
// EN_cpu_reset_server_response_get  I     1
// EN_set_verbosity               I     1
// EN_dm_dmi_read_addr            I     1
// EN_dm_dmi_write                I     1
// EN_dm_ndm_reset_req_get_get    I     1
// EN_dm_dmi_read_data            I     1
//
// Combinational paths from inputs to outputs:
//   (cpu_imem_master_awready, cpu_imem_master_wready) -> cpu_imem_master_bready
//   (cpu_imem_master_awready,
//    cpu_imem_master_wready,
//    cpu_dmem_master_awready,
//    cpu_dmem_master_wready) -> cpu_imem_master_rready
//   (cpu_imem_master_awready,
//    cpu_imem_master_wready,
//    cpu_dmem_master_awready,
//    cpu_dmem_master_wready) -> cpu_dmem_master_rready
//   (cpu_dmem_master_awready, cpu_dmem_master_wready) -> cpu_dmem_master_bready
//   (dm_dmi_read_addr_dm_addr,
//    dm_master_arready,
//    EN_dm_dmi_read_addr) -> RDY_dm_dmi_read_data
//   (dm_dmi_read_addr_dm_addr,
//    dm_master_arready,
//    EN_dm_dmi_read_addr,
//    EN_dm_dmi_read_data) -> dm_dmi_read_data
//   (dm_master_awready, dm_master_wready, dm_master_arready) -> RDY_dm_dmi_write
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCore(CLK,
	      RST_N,

	      EN_cpu_reset_server_request_put,
	      RDY_cpu_reset_server_request_put,

	      EN_cpu_reset_server_response_get,
	      RDY_cpu_reset_server_response_get,

	      cpu_imem_master_awvalid,

	      cpu_imem_master_awaddr,

	      cpu_imem_master_awprot,

	      cpu_imem_master_awready,

	      cpu_imem_master_wvalid,

	      cpu_imem_master_wdata,

	      cpu_imem_master_wstrb,

	      cpu_imem_master_wready,

	      cpu_imem_master_bvalid,
	      cpu_imem_master_bresp,

	      cpu_imem_master_bready,

	      cpu_imem_master_arvalid,

	      cpu_imem_master_araddr,

	      cpu_imem_master_arprot,

	      cpu_imem_master_arready,

	      cpu_imem_master_rvalid,
	      cpu_imem_master_rresp,
	      cpu_imem_master_rdata,

	      cpu_imem_master_rready,

	      cpu_dmem_master_awvalid,

	      cpu_dmem_master_awaddr,

	      cpu_dmem_master_awprot,

	      cpu_dmem_master_awready,

	      cpu_dmem_master_wvalid,

	      cpu_dmem_master_wdata,

	      cpu_dmem_master_wstrb,

	      cpu_dmem_master_wready,

	      cpu_dmem_master_bvalid,
	      cpu_dmem_master_bresp,

	      cpu_dmem_master_bready,

	      cpu_dmem_master_arvalid,

	      cpu_dmem_master_araddr,

	      cpu_dmem_master_arprot,

	      cpu_dmem_master_arready,

	      cpu_dmem_master_rvalid,
	      cpu_dmem_master_rresp,
	      cpu_dmem_master_rdata,

	      cpu_dmem_master_rready,

	      cpu_slave_awvalid,
	      cpu_slave_awaddr,
	      cpu_slave_awprot,

	      cpu_slave_awready,

	      cpu_slave_wvalid,
	      cpu_slave_wdata,
	      cpu_slave_wstrb,

	      cpu_slave_wready,

	      cpu_slave_bvalid,

	      cpu_slave_bresp,

	      cpu_slave_bready,

	      cpu_slave_arvalid,
	      cpu_slave_araddr,
	      cpu_slave_arprot,

	      cpu_slave_arready,

	      cpu_slave_rvalid,

	      cpu_slave_rresp,

	      cpu_slave_rdata,

	      cpu_slave_rready,

	      cpu_external_interrupt_req_set_not_clear,

	      set_verbosity_verbosity,
	      set_verbosity_logdelay,
	      EN_set_verbosity,
	      RDY_set_verbosity,

	      dm_dmi_read_addr_dm_addr,
	      EN_dm_dmi_read_addr,
	      RDY_dm_dmi_read_addr,

	      EN_dm_dmi_read_data,
	      dm_dmi_read_data,
	      RDY_dm_dmi_read_data,

	      dm_dmi_write_dm_addr,
	      dm_dmi_write_dm_word,
	      EN_dm_dmi_write,
	      RDY_dm_dmi_write,

	      EN_dm_ndm_reset_req_get_get,
	      RDY_dm_ndm_reset_req_get_get,

	      dm_master_awvalid,

	      dm_master_awaddr,

	      dm_master_awprot,

	      dm_master_awready,

	      dm_master_wvalid,

	      dm_master_wdata,

	      dm_master_wstrb,

	      dm_master_wready,

	      dm_master_bvalid,
	      dm_master_bresp,

	      dm_master_bready,

	      dm_master_arvalid,

	      dm_master_araddr,

	      dm_master_arprot,

	      dm_master_arready,

	      dm_master_rvalid,
	      dm_master_rresp,
	      dm_master_rdata,

	      dm_master_rready);
  input  CLK;
  input  RST_N;

  // action method cpu_reset_server_request_put
  input  EN_cpu_reset_server_request_put;
  output RDY_cpu_reset_server_request_put;

  // action method cpu_reset_server_response_get
  input  EN_cpu_reset_server_response_get;
  output RDY_cpu_reset_server_response_get;

  // value method cpu_imem_master_m_awvalid
  output cpu_imem_master_awvalid;

  // value method cpu_imem_master_m_awaddr
  output [63 : 0] cpu_imem_master_awaddr;

  // value method cpu_imem_master_m_awprot
  output [2 : 0] cpu_imem_master_awprot;

  // value method cpu_imem_master_m_awuser

  // action method cpu_imem_master_m_awready
  input  cpu_imem_master_awready;

  // value method cpu_imem_master_m_wvalid
  output cpu_imem_master_wvalid;

  // value method cpu_imem_master_m_wdata
  output [63 : 0] cpu_imem_master_wdata;

  // value method cpu_imem_master_m_wstrb
  output [7 : 0] cpu_imem_master_wstrb;

  // action method cpu_imem_master_m_wready
  input  cpu_imem_master_wready;

  // action method cpu_imem_master_m_bvalid
  input  cpu_imem_master_bvalid;
  input  [1 : 0] cpu_imem_master_bresp;

  // value method cpu_imem_master_m_bready
  output cpu_imem_master_bready;

  // value method cpu_imem_master_m_arvalid
  output cpu_imem_master_arvalid;

  // value method cpu_imem_master_m_araddr
  output [63 : 0] cpu_imem_master_araddr;

  // value method cpu_imem_master_m_arprot
  output [2 : 0] cpu_imem_master_arprot;

  // value method cpu_imem_master_m_aruser

  // action method cpu_imem_master_m_arready
  input  cpu_imem_master_arready;

  // action method cpu_imem_master_m_rvalid
  input  cpu_imem_master_rvalid;
  input  [1 : 0] cpu_imem_master_rresp;
  input  [63 : 0] cpu_imem_master_rdata;

  // value method cpu_imem_master_m_rready
  output cpu_imem_master_rready;

  // value method cpu_dmem_master_m_awvalid
  output cpu_dmem_master_awvalid;

  // value method cpu_dmem_master_m_awaddr
  output [63 : 0] cpu_dmem_master_awaddr;

  // value method cpu_dmem_master_m_awprot
  output [2 : 0] cpu_dmem_master_awprot;

  // value method cpu_dmem_master_m_awuser

  // action method cpu_dmem_master_m_awready
  input  cpu_dmem_master_awready;

  // value method cpu_dmem_master_m_wvalid
  output cpu_dmem_master_wvalid;

  // value method cpu_dmem_master_m_wdata
  output [63 : 0] cpu_dmem_master_wdata;

  // value method cpu_dmem_master_m_wstrb
  output [7 : 0] cpu_dmem_master_wstrb;

  // action method cpu_dmem_master_m_wready
  input  cpu_dmem_master_wready;

  // action method cpu_dmem_master_m_bvalid
  input  cpu_dmem_master_bvalid;
  input  [1 : 0] cpu_dmem_master_bresp;

  // value method cpu_dmem_master_m_bready
  output cpu_dmem_master_bready;

  // value method cpu_dmem_master_m_arvalid
  output cpu_dmem_master_arvalid;

  // value method cpu_dmem_master_m_araddr
  output [63 : 0] cpu_dmem_master_araddr;

  // value method cpu_dmem_master_m_arprot
  output [2 : 0] cpu_dmem_master_arprot;

  // value method cpu_dmem_master_m_aruser

  // action method cpu_dmem_master_m_arready
  input  cpu_dmem_master_arready;

  // action method cpu_dmem_master_m_rvalid
  input  cpu_dmem_master_rvalid;
  input  [1 : 0] cpu_dmem_master_rresp;
  input  [63 : 0] cpu_dmem_master_rdata;

  // value method cpu_dmem_master_m_rready
  output cpu_dmem_master_rready;

  // action method cpu_slave_m_awvalid
  input  cpu_slave_awvalid;
  input  [63 : 0] cpu_slave_awaddr;
  input  [2 : 0] cpu_slave_awprot;

  // value method cpu_slave_m_awready
  output cpu_slave_awready;

  // action method cpu_slave_m_wvalid
  input  cpu_slave_wvalid;
  input  [63 : 0] cpu_slave_wdata;
  input  [7 : 0] cpu_slave_wstrb;

  // value method cpu_slave_m_wready
  output cpu_slave_wready;

  // value method cpu_slave_m_bvalid
  output cpu_slave_bvalid;

  // value method cpu_slave_m_bresp
  output [1 : 0] cpu_slave_bresp;

  // value method cpu_slave_m_buser

  // action method cpu_slave_m_bready
  input  cpu_slave_bready;

  // action method cpu_slave_m_arvalid
  input  cpu_slave_arvalid;
  input  [63 : 0] cpu_slave_araddr;
  input  [2 : 0] cpu_slave_arprot;

  // value method cpu_slave_m_arready
  output cpu_slave_arready;

  // value method cpu_slave_m_rvalid
  output cpu_slave_rvalid;

  // value method cpu_slave_m_rresp
  output [1 : 0] cpu_slave_rresp;

  // value method cpu_slave_m_rdata
  output [63 : 0] cpu_slave_rdata;

  // value method cpu_slave_m_ruser

  // action method cpu_slave_m_rready
  input  cpu_slave_rready;

  // action method cpu_external_interrupt_req
  input  cpu_external_interrupt_req_set_not_clear;

  // action method set_verbosity
  input  [3 : 0] set_verbosity_verbosity;
  input  [63 : 0] set_verbosity_logdelay;
  input  EN_set_verbosity;
  output RDY_set_verbosity;

  // action method dm_dmi_read_addr
  input  [6 : 0] dm_dmi_read_addr_dm_addr;
  input  EN_dm_dmi_read_addr;
  output RDY_dm_dmi_read_addr;

  // actionvalue method dm_dmi_read_data
  input  EN_dm_dmi_read_data;
  output [31 : 0] dm_dmi_read_data;
  output RDY_dm_dmi_read_data;

  // action method dm_dmi_write
  input  [6 : 0] dm_dmi_write_dm_addr;
  input  [31 : 0] dm_dmi_write_dm_word;
  input  EN_dm_dmi_write;
  output RDY_dm_dmi_write;

  // action method dm_ndm_reset_req_get_get
  input  EN_dm_ndm_reset_req_get_get;
  output RDY_dm_ndm_reset_req_get_get;

  // value method dm_master_m_awvalid
  output dm_master_awvalid;

  // value method dm_master_m_awaddr
  output [63 : 0] dm_master_awaddr;

  // value method dm_master_m_awprot
  output [2 : 0] dm_master_awprot;

  // value method dm_master_m_awuser

  // action method dm_master_m_awready
  input  dm_master_awready;

  // value method dm_master_m_wvalid
  output dm_master_wvalid;

  // value method dm_master_m_wdata
  output [63 : 0] dm_master_wdata;

  // value method dm_master_m_wstrb
  output [7 : 0] dm_master_wstrb;

  // action method dm_master_m_wready
  input  dm_master_wready;

  // action method dm_master_m_bvalid
  input  dm_master_bvalid;
  input  [1 : 0] dm_master_bresp;

  // value method dm_master_m_bready
  output dm_master_bready;

  // value method dm_master_m_arvalid
  output dm_master_arvalid;

  // value method dm_master_m_araddr
  output [63 : 0] dm_master_araddr;

  // value method dm_master_m_arprot
  output [2 : 0] dm_master_arprot;

  // value method dm_master_m_aruser

  // action method dm_master_m_arready
  input  dm_master_arready;

  // action method dm_master_m_rvalid
  input  dm_master_rvalid;
  input  [1 : 0] dm_master_rresp;
  input  [63 : 0] dm_master_rdata;

  // value method dm_master_m_rready
  output dm_master_rready;

  // signals for module outputs
  wire [63 : 0] cpu_dmem_master_araddr,
		cpu_dmem_master_awaddr,
		cpu_dmem_master_wdata,
		cpu_imem_master_araddr,
		cpu_imem_master_awaddr,
		cpu_imem_master_wdata,
		cpu_slave_rdata,
		dm_master_araddr,
		dm_master_awaddr,
		dm_master_wdata;
  wire [31 : 0] dm_dmi_read_data;
  wire [7 : 0] cpu_dmem_master_wstrb, cpu_imem_master_wstrb, dm_master_wstrb;
  wire [2 : 0] cpu_dmem_master_arprot,
	       cpu_dmem_master_awprot,
	       cpu_imem_master_arprot,
	       cpu_imem_master_awprot,
	       dm_master_arprot,
	       dm_master_awprot;
  wire [1 : 0] cpu_slave_bresp, cpu_slave_rresp;
  wire RDY_cpu_reset_server_request_put,
       RDY_cpu_reset_server_response_get,
       RDY_dm_dmi_read_addr,
       RDY_dm_dmi_read_data,
       RDY_dm_dmi_write,
       RDY_dm_ndm_reset_req_get_get,
       RDY_set_verbosity,
       cpu_dmem_master_arvalid,
       cpu_dmem_master_awvalid,
       cpu_dmem_master_bready,
       cpu_dmem_master_rready,
       cpu_dmem_master_wvalid,
       cpu_imem_master_arvalid,
       cpu_imem_master_awvalid,
       cpu_imem_master_bready,
       cpu_imem_master_rready,
       cpu_imem_master_wvalid,
       cpu_slave_arready,
       cpu_slave_awready,
       cpu_slave_bvalid,
       cpu_slave_rvalid,
       cpu_slave_wready,
       dm_master_arvalid,
       dm_master_awvalid,
       dm_master_bready,
       dm_master_rready,
       dm_master_wvalid;

  // ports of submodule cpu
  wire [63 : 0] cpu$dmem_master_araddr,
		cpu$dmem_master_awaddr,
		cpu$dmem_master_rdata,
		cpu$dmem_master_wdata,
		cpu$imem_master_araddr,
		cpu$imem_master_awaddr,
		cpu$imem_master_rdata,
		cpu$imem_master_wdata,
		cpu$near_mem_slave_araddr,
		cpu$near_mem_slave_awaddr,
		cpu$near_mem_slave_rdata,
		cpu$near_mem_slave_wdata,
		cpu$set_verbosity_logdelay;
  wire [48 : 0] cpu$hart0_csr_mem_server_request_put;
  wire [41 : 0] cpu$hart0_gpr_mem_server_request_put;
  wire [31 : 0] cpu$hart0_csr_mem_server_response_get,
		cpu$hart0_gpr_mem_server_response_get;
  wire [7 : 0] cpu$dmem_master_wstrb,
	       cpu$imem_master_wstrb,
	       cpu$near_mem_slave_wstrb;
  wire [3 : 0] cpu$hart0_put_other_req_put, cpu$set_verbosity_verbosity;
  wire [2 : 0] cpu$dmem_master_arprot,
	       cpu$dmem_master_awprot,
	       cpu$imem_master_arprot,
	       cpu$imem_master_awprot,
	       cpu$near_mem_slave_arprot,
	       cpu$near_mem_slave_awprot;
  wire [1 : 0] cpu$dmem_master_bresp,
	       cpu$dmem_master_rresp,
	       cpu$imem_master_bresp,
	       cpu$imem_master_rresp,
	       cpu$near_mem_slave_bresp,
	       cpu$near_mem_slave_rresp;
  wire cpu$EN_hart0_csr_mem_server_request_put,
       cpu$EN_hart0_csr_mem_server_response_get,
       cpu$EN_hart0_gpr_mem_server_request_put,
       cpu$EN_hart0_gpr_mem_server_response_get,
       cpu$EN_hart0_put_other_req_put,
       cpu$EN_hart0_server_reset_request_put,
       cpu$EN_hart0_server_reset_response_get,
       cpu$EN_hart0_server_run_halt_request_put,
       cpu$EN_hart0_server_run_halt_response_get,
       cpu$EN_set_verbosity,
       cpu$RDY_hart0_csr_mem_server_request_put,
       cpu$RDY_hart0_csr_mem_server_response_get,
       cpu$RDY_hart0_gpr_mem_server_request_put,
       cpu$RDY_hart0_gpr_mem_server_response_get,
       cpu$RDY_hart0_server_reset_request_put,
       cpu$RDY_hart0_server_reset_response_get,
       cpu$RDY_hart0_server_run_halt_request_put,
       cpu$RDY_hart0_server_run_halt_response_get,
       cpu$dmem_master_arready,
       cpu$dmem_master_arvalid,
       cpu$dmem_master_awready,
       cpu$dmem_master_awvalid,
       cpu$dmem_master_bready,
       cpu$dmem_master_bvalid,
       cpu$dmem_master_rready,
       cpu$dmem_master_rvalid,
       cpu$dmem_master_wready,
       cpu$dmem_master_wvalid,
       cpu$external_interrupt_req_set_not_clear,
       cpu$hart0_server_run_halt_request_put,
       cpu$hart0_server_run_halt_response_get,
       cpu$imem_master_arready,
       cpu$imem_master_arvalid,
       cpu$imem_master_awready,
       cpu$imem_master_awvalid,
       cpu$imem_master_bready,
       cpu$imem_master_bvalid,
       cpu$imem_master_rready,
       cpu$imem_master_rvalid,
       cpu$imem_master_wready,
       cpu$imem_master_wvalid,
       cpu$near_mem_slave_arready,
       cpu$near_mem_slave_arvalid,
       cpu$near_mem_slave_awready,
       cpu$near_mem_slave_awvalid,
       cpu$near_mem_slave_bready,
       cpu$near_mem_slave_bvalid,
       cpu$near_mem_slave_rready,
       cpu$near_mem_slave_rvalid,
       cpu$near_mem_slave_wready,
       cpu$near_mem_slave_wvalid;

  // ports of submodule debug_module
  wire [63 : 0] debug_module$master_araddr,
		debug_module$master_awaddr,
		debug_module$master_rdata,
		debug_module$master_wdata;
  wire [48 : 0] debug_module$hart0_csr_mem_client_request_get;
  wire [41 : 0] debug_module$hart0_gpr_mem_client_request_get;
  wire [31 : 0] debug_module$dmi_read_data,
		debug_module$dmi_write_dm_word,
		debug_module$hart0_csr_mem_client_response_put,
		debug_module$hart0_gpr_mem_client_response_put;
  wire [7 : 0] debug_module$master_wstrb;
  wire [6 : 0] debug_module$dmi_read_addr_dm_addr,
	       debug_module$dmi_write_dm_addr;
  wire [3 : 0] debug_module$hart0_get_other_req_get;
  wire [2 : 0] debug_module$master_arprot, debug_module$master_awprot;
  wire [1 : 0] debug_module$master_bresp, debug_module$master_rresp;
  wire debug_module$EN_dmi_read_addr,
       debug_module$EN_dmi_read_data,
       debug_module$EN_dmi_write,
       debug_module$EN_get_ndm_reset_req_get,
       debug_module$EN_hart0_client_run_halt_request_get,
       debug_module$EN_hart0_client_run_halt_response_put,
       debug_module$EN_hart0_csr_mem_client_request_get,
       debug_module$EN_hart0_csr_mem_client_response_put,
       debug_module$EN_hart0_get_other_req_get,
       debug_module$EN_hart0_get_reset_req_get,
       debug_module$EN_hart0_gpr_mem_client_request_get,
       debug_module$EN_hart0_gpr_mem_client_response_put,
       debug_module$RDY_dmi_read_addr,
       debug_module$RDY_dmi_read_data,
       debug_module$RDY_dmi_write,
       debug_module$RDY_get_ndm_reset_req_get,
       debug_module$RDY_hart0_client_run_halt_request_get,
       debug_module$RDY_hart0_client_run_halt_response_put,
       debug_module$RDY_hart0_csr_mem_client_request_get,
       debug_module$RDY_hart0_csr_mem_client_response_put,
       debug_module$RDY_hart0_get_other_req_get,
       debug_module$RDY_hart0_get_reset_req_get,
       debug_module$RDY_hart0_gpr_mem_client_request_get,
       debug_module$RDY_hart0_gpr_mem_client_response_put,
       debug_module$hart0_client_run_halt_request_get,
       debug_module$hart0_client_run_halt_response_put,
       debug_module$master_arready,
       debug_module$master_arvalid,
       debug_module$master_awready,
       debug_module$master_awvalid,
       debug_module$master_bready,
       debug_module$master_bvalid,
       debug_module$master_rready,
       debug_module$master_rvalid,
       debug_module$master_wready,
       debug_module$master_wvalid;

  // ports of submodule f_reset_reqs
  wire f_reset_reqs$CLR,
       f_reset_reqs$DEQ,
       f_reset_reqs$EMPTY_N,
       f_reset_reqs$ENQ,
       f_reset_reqs$FULL_N;

  // ports of submodule f_reset_requestor
  wire f_reset_requestor$CLR,
       f_reset_requestor$DEQ,
       f_reset_requestor$D_IN,
       f_reset_requestor$D_OUT,
       f_reset_requestor$EMPTY_N,
       f_reset_requestor$ENQ,
       f_reset_requestor$FULL_N;

  // ports of submodule f_reset_rsps
  wire f_reset_rsps$CLR,
       f_reset_rsps$DEQ,
       f_reset_rsps$EMPTY_N,
       f_reset_rsps$ENQ,
       f_reset_rsps$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_ClientServerRequest,
       CAN_FIRE_RL_ClientServerRequest_1,
       CAN_FIRE_RL_ClientServerRequest_2,
       CAN_FIRE_RL_ClientServerResponse,
       CAN_FIRE_RL_ClientServerResponse_1,
       CAN_FIRE_RL_ClientServerResponse_2,
       CAN_FIRE_RL_mkConnectionGetPut,
       CAN_FIRE_RL_rl_cpu_hart0_reset_complete,
       CAN_FIRE_RL_rl_cpu_hart0_reset_from_dm_start,
       CAN_FIRE_RL_rl_cpu_hart0_reset_from_soc_start,
       CAN_FIRE_cpu_dmem_master_m_arready,
       CAN_FIRE_cpu_dmem_master_m_awready,
       CAN_FIRE_cpu_dmem_master_m_bvalid,
       CAN_FIRE_cpu_dmem_master_m_rvalid,
       CAN_FIRE_cpu_dmem_master_m_wready,
       CAN_FIRE_cpu_external_interrupt_req,
       CAN_FIRE_cpu_imem_master_m_arready,
       CAN_FIRE_cpu_imem_master_m_awready,
       CAN_FIRE_cpu_imem_master_m_bvalid,
       CAN_FIRE_cpu_imem_master_m_rvalid,
       CAN_FIRE_cpu_imem_master_m_wready,
       CAN_FIRE_cpu_reset_server_request_put,
       CAN_FIRE_cpu_reset_server_response_get,
       CAN_FIRE_cpu_slave_m_arvalid,
       CAN_FIRE_cpu_slave_m_awvalid,
       CAN_FIRE_cpu_slave_m_bready,
       CAN_FIRE_cpu_slave_m_rready,
       CAN_FIRE_cpu_slave_m_wvalid,
       CAN_FIRE_dm_dmi_read_addr,
       CAN_FIRE_dm_dmi_read_data,
       CAN_FIRE_dm_dmi_write,
       CAN_FIRE_dm_master_m_arready,
       CAN_FIRE_dm_master_m_awready,
       CAN_FIRE_dm_master_m_bvalid,
       CAN_FIRE_dm_master_m_rvalid,
       CAN_FIRE_dm_master_m_wready,
       CAN_FIRE_dm_ndm_reset_req_get_get,
       CAN_FIRE_set_verbosity,
       WILL_FIRE_RL_ClientServerRequest,
       WILL_FIRE_RL_ClientServerRequest_1,
       WILL_FIRE_RL_ClientServerRequest_2,
       WILL_FIRE_RL_ClientServerResponse,
       WILL_FIRE_RL_ClientServerResponse_1,
       WILL_FIRE_RL_ClientServerResponse_2,
       WILL_FIRE_RL_mkConnectionGetPut,
       WILL_FIRE_RL_rl_cpu_hart0_reset_complete,
       WILL_FIRE_RL_rl_cpu_hart0_reset_from_dm_start,
       WILL_FIRE_RL_rl_cpu_hart0_reset_from_soc_start,
       WILL_FIRE_cpu_dmem_master_m_arready,
       WILL_FIRE_cpu_dmem_master_m_awready,
       WILL_FIRE_cpu_dmem_master_m_bvalid,
       WILL_FIRE_cpu_dmem_master_m_rvalid,
       WILL_FIRE_cpu_dmem_master_m_wready,
       WILL_FIRE_cpu_external_interrupt_req,
       WILL_FIRE_cpu_imem_master_m_arready,
       WILL_FIRE_cpu_imem_master_m_awready,
       WILL_FIRE_cpu_imem_master_m_bvalid,
       WILL_FIRE_cpu_imem_master_m_rvalid,
       WILL_FIRE_cpu_imem_master_m_wready,
       WILL_FIRE_cpu_reset_server_request_put,
       WILL_FIRE_cpu_reset_server_response_get,
       WILL_FIRE_cpu_slave_m_arvalid,
       WILL_FIRE_cpu_slave_m_awvalid,
       WILL_FIRE_cpu_slave_m_bready,
       WILL_FIRE_cpu_slave_m_rready,
       WILL_FIRE_cpu_slave_m_wvalid,
       WILL_FIRE_dm_dmi_read_addr,
       WILL_FIRE_dm_dmi_read_data,
       WILL_FIRE_dm_dmi_write,
       WILL_FIRE_dm_master_m_arready,
       WILL_FIRE_dm_master_m_awready,
       WILL_FIRE_dm_master_m_bvalid,
       WILL_FIRE_dm_master_m_rvalid,
       WILL_FIRE_dm_master_m_wready,
       WILL_FIRE_dm_ndm_reset_req_get_get,
       WILL_FIRE_set_verbosity;

  // action method cpu_reset_server_request_put
  assign RDY_cpu_reset_server_request_put = f_reset_reqs$FULL_N ;
  assign CAN_FIRE_cpu_reset_server_request_put = f_reset_reqs$FULL_N ;
  assign WILL_FIRE_cpu_reset_server_request_put =
	     EN_cpu_reset_server_request_put ;

  // action method cpu_reset_server_response_get
  assign RDY_cpu_reset_server_response_get = f_reset_rsps$EMPTY_N ;
  assign CAN_FIRE_cpu_reset_server_response_get = f_reset_rsps$EMPTY_N ;
  assign WILL_FIRE_cpu_reset_server_response_get =
	     EN_cpu_reset_server_response_get ;

  // value method cpu_imem_master_m_awvalid
  assign cpu_imem_master_awvalid = cpu$imem_master_awvalid ;

  // value method cpu_imem_master_m_awaddr
  assign cpu_imem_master_awaddr = cpu$imem_master_awaddr ;

  // value method cpu_imem_master_m_awprot
  assign cpu_imem_master_awprot = cpu$imem_master_awprot ;

  // action method cpu_imem_master_m_awready
  assign CAN_FIRE_cpu_imem_master_m_awready = 1'd1 ;
  assign WILL_FIRE_cpu_imem_master_m_awready = 1'd1 ;

  // value method cpu_imem_master_m_wvalid
  assign cpu_imem_master_wvalid = cpu$imem_master_wvalid ;

  // value method cpu_imem_master_m_wdata
  assign cpu_imem_master_wdata = cpu$imem_master_wdata ;

  // value method cpu_imem_master_m_wstrb
  assign cpu_imem_master_wstrb = cpu$imem_master_wstrb ;

  // action method cpu_imem_master_m_wready
  assign CAN_FIRE_cpu_imem_master_m_wready = 1'd1 ;
  assign WILL_FIRE_cpu_imem_master_m_wready = 1'd1 ;

  // action method cpu_imem_master_m_bvalid
  assign CAN_FIRE_cpu_imem_master_m_bvalid = 1'd1 ;
  assign WILL_FIRE_cpu_imem_master_m_bvalid = 1'd1 ;

  // value method cpu_imem_master_m_bready
  assign cpu_imem_master_bready = cpu$imem_master_bready ;

  // value method cpu_imem_master_m_arvalid
  assign cpu_imem_master_arvalid = cpu$imem_master_arvalid ;

  // value method cpu_imem_master_m_araddr
  assign cpu_imem_master_araddr = cpu$imem_master_araddr ;

  // value method cpu_imem_master_m_arprot
  assign cpu_imem_master_arprot = cpu$imem_master_arprot ;

  // action method cpu_imem_master_m_arready
  assign CAN_FIRE_cpu_imem_master_m_arready = 1'd1 ;
  assign WILL_FIRE_cpu_imem_master_m_arready = 1'd1 ;

  // action method cpu_imem_master_m_rvalid
  assign CAN_FIRE_cpu_imem_master_m_rvalid = 1'd1 ;
  assign WILL_FIRE_cpu_imem_master_m_rvalid = 1'd1 ;

  // value method cpu_imem_master_m_rready
  assign cpu_imem_master_rready = cpu$imem_master_rready ;

  // value method cpu_dmem_master_m_awvalid
  assign cpu_dmem_master_awvalid = cpu$dmem_master_awvalid ;

  // value method cpu_dmem_master_m_awaddr
  assign cpu_dmem_master_awaddr = cpu$dmem_master_awaddr ;

  // value method cpu_dmem_master_m_awprot
  assign cpu_dmem_master_awprot = cpu$dmem_master_awprot ;

  // action method cpu_dmem_master_m_awready
  assign CAN_FIRE_cpu_dmem_master_m_awready = 1'd1 ;
  assign WILL_FIRE_cpu_dmem_master_m_awready = 1'd1 ;

  // value method cpu_dmem_master_m_wvalid
  assign cpu_dmem_master_wvalid = cpu$dmem_master_wvalid ;

  // value method cpu_dmem_master_m_wdata
  assign cpu_dmem_master_wdata = cpu$dmem_master_wdata ;

  // value method cpu_dmem_master_m_wstrb
  assign cpu_dmem_master_wstrb = cpu$dmem_master_wstrb ;

  // action method cpu_dmem_master_m_wready
  assign CAN_FIRE_cpu_dmem_master_m_wready = 1'd1 ;
  assign WILL_FIRE_cpu_dmem_master_m_wready = 1'd1 ;

  // action method cpu_dmem_master_m_bvalid
  assign CAN_FIRE_cpu_dmem_master_m_bvalid = 1'd1 ;
  assign WILL_FIRE_cpu_dmem_master_m_bvalid = 1'd1 ;

  // value method cpu_dmem_master_m_bready
  assign cpu_dmem_master_bready = cpu$dmem_master_bready ;

  // value method cpu_dmem_master_m_arvalid
  assign cpu_dmem_master_arvalid = cpu$dmem_master_arvalid ;

  // value method cpu_dmem_master_m_araddr
  assign cpu_dmem_master_araddr = cpu$dmem_master_araddr ;

  // value method cpu_dmem_master_m_arprot
  assign cpu_dmem_master_arprot = cpu$dmem_master_arprot ;

  // action method cpu_dmem_master_m_arready
  assign CAN_FIRE_cpu_dmem_master_m_arready = 1'd1 ;
  assign WILL_FIRE_cpu_dmem_master_m_arready = 1'd1 ;

  // action method cpu_dmem_master_m_rvalid
  assign CAN_FIRE_cpu_dmem_master_m_rvalid = 1'd1 ;
  assign WILL_FIRE_cpu_dmem_master_m_rvalid = 1'd1 ;

  // value method cpu_dmem_master_m_rready
  assign cpu_dmem_master_rready = cpu$dmem_master_rready ;

  // action method cpu_slave_m_awvalid
  assign CAN_FIRE_cpu_slave_m_awvalid = 1'd1 ;
  assign WILL_FIRE_cpu_slave_m_awvalid = 1'd1 ;

  // value method cpu_slave_m_awready
  assign cpu_slave_awready = cpu$near_mem_slave_awready ;

  // action method cpu_slave_m_wvalid
  assign CAN_FIRE_cpu_slave_m_wvalid = 1'd1 ;
  assign WILL_FIRE_cpu_slave_m_wvalid = 1'd1 ;

  // value method cpu_slave_m_wready
  assign cpu_slave_wready = cpu$near_mem_slave_wready ;

  // value method cpu_slave_m_bvalid
  assign cpu_slave_bvalid = cpu$near_mem_slave_bvalid ;

  // value method cpu_slave_m_bresp
  assign cpu_slave_bresp = cpu$near_mem_slave_bresp ;

  // action method cpu_slave_m_bready
  assign CAN_FIRE_cpu_slave_m_bready = 1'd1 ;
  assign WILL_FIRE_cpu_slave_m_bready = 1'd1 ;

  // action method cpu_slave_m_arvalid
  assign CAN_FIRE_cpu_slave_m_arvalid = 1'd1 ;
  assign WILL_FIRE_cpu_slave_m_arvalid = 1'd1 ;

  // value method cpu_slave_m_arready
  assign cpu_slave_arready = cpu$near_mem_slave_arready ;

  // value method cpu_slave_m_rvalid
  assign cpu_slave_rvalid = cpu$near_mem_slave_rvalid ;

  // value method cpu_slave_m_rresp
  assign cpu_slave_rresp = cpu$near_mem_slave_rresp ;

  // value method cpu_slave_m_rdata
  assign cpu_slave_rdata = cpu$near_mem_slave_rdata ;

  // action method cpu_slave_m_rready
  assign CAN_FIRE_cpu_slave_m_rready = 1'd1 ;
  assign WILL_FIRE_cpu_slave_m_rready = 1'd1 ;

  // action method cpu_external_interrupt_req
  assign CAN_FIRE_cpu_external_interrupt_req = 1'd1 ;
  assign WILL_FIRE_cpu_external_interrupt_req = 1'd1 ;

  // action method set_verbosity
  assign RDY_set_verbosity = 1'd1 ;
  assign CAN_FIRE_set_verbosity = 1'd1 ;
  assign WILL_FIRE_set_verbosity = EN_set_verbosity ;

  // action method dm_dmi_read_addr
  assign RDY_dm_dmi_read_addr = debug_module$RDY_dmi_read_addr ;
  assign CAN_FIRE_dm_dmi_read_addr = debug_module$RDY_dmi_read_addr ;
  assign WILL_FIRE_dm_dmi_read_addr = EN_dm_dmi_read_addr ;

  // actionvalue method dm_dmi_read_data
  assign dm_dmi_read_data = debug_module$dmi_read_data ;
  assign RDY_dm_dmi_read_data = debug_module$RDY_dmi_read_data ;
  assign CAN_FIRE_dm_dmi_read_data = debug_module$RDY_dmi_read_data ;
  assign WILL_FIRE_dm_dmi_read_data = EN_dm_dmi_read_data ;

  // action method dm_dmi_write
  assign RDY_dm_dmi_write = debug_module$RDY_dmi_write ;
  assign CAN_FIRE_dm_dmi_write = debug_module$RDY_dmi_write ;
  assign WILL_FIRE_dm_dmi_write = EN_dm_dmi_write ;

  // action method dm_ndm_reset_req_get_get
  assign RDY_dm_ndm_reset_req_get_get =
	     debug_module$RDY_get_ndm_reset_req_get ;
  assign CAN_FIRE_dm_ndm_reset_req_get_get =
	     debug_module$RDY_get_ndm_reset_req_get ;
  assign WILL_FIRE_dm_ndm_reset_req_get_get = EN_dm_ndm_reset_req_get_get ;

  // value method dm_master_m_awvalid
  assign dm_master_awvalid = debug_module$master_awvalid ;

  // value method dm_master_m_awaddr
  assign dm_master_awaddr = debug_module$master_awaddr ;

  // value method dm_master_m_awprot
  assign dm_master_awprot = debug_module$master_awprot ;

  // action method dm_master_m_awready
  assign CAN_FIRE_dm_master_m_awready = 1'd1 ;
  assign WILL_FIRE_dm_master_m_awready = 1'd1 ;

  // value method dm_master_m_wvalid
  assign dm_master_wvalid = debug_module$master_wvalid ;

  // value method dm_master_m_wdata
  assign dm_master_wdata = debug_module$master_wdata ;

  // value method dm_master_m_wstrb
  assign dm_master_wstrb = debug_module$master_wstrb ;

  // action method dm_master_m_wready
  assign CAN_FIRE_dm_master_m_wready = 1'd1 ;
  assign WILL_FIRE_dm_master_m_wready = 1'd1 ;

  // action method dm_master_m_bvalid
  assign CAN_FIRE_dm_master_m_bvalid = 1'd1 ;
  assign WILL_FIRE_dm_master_m_bvalid = 1'd1 ;

  // value method dm_master_m_bready
  assign dm_master_bready = debug_module$master_bready ;

  // value method dm_master_m_arvalid
  assign dm_master_arvalid = debug_module$master_arvalid ;

  // value method dm_master_m_araddr
  assign dm_master_araddr = debug_module$master_araddr ;

  // value method dm_master_m_arprot
  assign dm_master_arprot = debug_module$master_arprot ;

  // action method dm_master_m_arready
  assign CAN_FIRE_dm_master_m_arready = 1'd1 ;
  assign WILL_FIRE_dm_master_m_arready = 1'd1 ;

  // action method dm_master_m_rvalid
  assign CAN_FIRE_dm_master_m_rvalid = 1'd1 ;
  assign WILL_FIRE_dm_master_m_rvalid = 1'd1 ;

  // value method dm_master_m_rready
  assign dm_master_rready = debug_module$master_rready ;

  // submodule cpu
  mkCPU cpu(.CLK(CLK),
	    .RST_N(RST_N),
	    .dmem_master_arready(cpu$dmem_master_arready),
	    .dmem_master_awready(cpu$dmem_master_awready),
	    .dmem_master_bresp(cpu$dmem_master_bresp),
	    .dmem_master_bvalid(cpu$dmem_master_bvalid),
	    .dmem_master_rdata(cpu$dmem_master_rdata),
	    .dmem_master_rresp(cpu$dmem_master_rresp),
	    .dmem_master_rvalid(cpu$dmem_master_rvalid),
	    .dmem_master_wready(cpu$dmem_master_wready),
	    .external_interrupt_req_set_not_clear(cpu$external_interrupt_req_set_not_clear),
	    .hart0_csr_mem_server_request_put(cpu$hart0_csr_mem_server_request_put),
	    .hart0_gpr_mem_server_request_put(cpu$hart0_gpr_mem_server_request_put),
	    .hart0_put_other_req_put(cpu$hart0_put_other_req_put),
	    .hart0_server_run_halt_request_put(cpu$hart0_server_run_halt_request_put),
	    .imem_master_arready(cpu$imem_master_arready),
	    .imem_master_awready(cpu$imem_master_awready),
	    .imem_master_bresp(cpu$imem_master_bresp),
	    .imem_master_bvalid(cpu$imem_master_bvalid),
	    .imem_master_rdata(cpu$imem_master_rdata),
	    .imem_master_rresp(cpu$imem_master_rresp),
	    .imem_master_rvalid(cpu$imem_master_rvalid),
	    .imem_master_wready(cpu$imem_master_wready),
	    .near_mem_slave_araddr(cpu$near_mem_slave_araddr),
	    .near_mem_slave_arprot(cpu$near_mem_slave_arprot),
	    .near_mem_slave_arvalid(cpu$near_mem_slave_arvalid),
	    .near_mem_slave_awaddr(cpu$near_mem_slave_awaddr),
	    .near_mem_slave_awprot(cpu$near_mem_slave_awprot),
	    .near_mem_slave_awvalid(cpu$near_mem_slave_awvalid),
	    .near_mem_slave_bready(cpu$near_mem_slave_bready),
	    .near_mem_slave_rready(cpu$near_mem_slave_rready),
	    .near_mem_slave_wdata(cpu$near_mem_slave_wdata),
	    .near_mem_slave_wstrb(cpu$near_mem_slave_wstrb),
	    .near_mem_slave_wvalid(cpu$near_mem_slave_wvalid),
	    .set_verbosity_logdelay(cpu$set_verbosity_logdelay),
	    .set_verbosity_verbosity(cpu$set_verbosity_verbosity),
	    .EN_hart0_server_reset_request_put(cpu$EN_hart0_server_reset_request_put),
	    .EN_hart0_server_reset_response_get(cpu$EN_hart0_server_reset_response_get),
	    .EN_set_verbosity(cpu$EN_set_verbosity),
	    .EN_hart0_server_run_halt_request_put(cpu$EN_hart0_server_run_halt_request_put),
	    .EN_hart0_server_run_halt_response_get(cpu$EN_hart0_server_run_halt_response_get),
	    .EN_hart0_put_other_req_put(cpu$EN_hart0_put_other_req_put),
	    .EN_hart0_gpr_mem_server_request_put(cpu$EN_hart0_gpr_mem_server_request_put),
	    .EN_hart0_gpr_mem_server_response_get(cpu$EN_hart0_gpr_mem_server_response_get),
	    .EN_hart0_csr_mem_server_request_put(cpu$EN_hart0_csr_mem_server_request_put),
	    .EN_hart0_csr_mem_server_response_get(cpu$EN_hart0_csr_mem_server_response_get),
	    .RDY_hart0_server_reset_request_put(cpu$RDY_hart0_server_reset_request_put),
	    .RDY_hart0_server_reset_response_get(cpu$RDY_hart0_server_reset_response_get),
	    .imem_master_awvalid(cpu$imem_master_awvalid),
	    .imem_master_awaddr(cpu$imem_master_awaddr),
	    .imem_master_awprot(cpu$imem_master_awprot),
	    .imem_master_wvalid(cpu$imem_master_wvalid),
	    .imem_master_wdata(cpu$imem_master_wdata),
	    .imem_master_wstrb(cpu$imem_master_wstrb),
	    .imem_master_bready(cpu$imem_master_bready),
	    .imem_master_arvalid(cpu$imem_master_arvalid),
	    .imem_master_araddr(cpu$imem_master_araddr),
	    .imem_master_arprot(cpu$imem_master_arprot),
	    .imem_master_rready(cpu$imem_master_rready),
	    .dmem_master_awvalid(cpu$dmem_master_awvalid),
	    .dmem_master_awaddr(cpu$dmem_master_awaddr),
	    .dmem_master_awprot(cpu$dmem_master_awprot),
	    .dmem_master_wvalid(cpu$dmem_master_wvalid),
	    .dmem_master_wdata(cpu$dmem_master_wdata),
	    .dmem_master_wstrb(cpu$dmem_master_wstrb),
	    .dmem_master_bready(cpu$dmem_master_bready),
	    .dmem_master_arvalid(cpu$dmem_master_arvalid),
	    .dmem_master_araddr(cpu$dmem_master_araddr),
	    .dmem_master_arprot(cpu$dmem_master_arprot),
	    .dmem_master_rready(cpu$dmem_master_rready),
	    .near_mem_slave_awready(cpu$near_mem_slave_awready),
	    .near_mem_slave_wready(cpu$near_mem_slave_wready),
	    .near_mem_slave_bvalid(cpu$near_mem_slave_bvalid),
	    .near_mem_slave_bresp(cpu$near_mem_slave_bresp),
	    .near_mem_slave_arready(cpu$near_mem_slave_arready),
	    .near_mem_slave_rvalid(cpu$near_mem_slave_rvalid),
	    .near_mem_slave_rresp(cpu$near_mem_slave_rresp),
	    .near_mem_slave_rdata(cpu$near_mem_slave_rdata),
	    .RDY_set_verbosity(),
	    .RDY_hart0_server_run_halt_request_put(cpu$RDY_hart0_server_run_halt_request_put),
	    .hart0_server_run_halt_response_get(cpu$hart0_server_run_halt_response_get),
	    .RDY_hart0_server_run_halt_response_get(cpu$RDY_hart0_server_run_halt_response_get),
	    .RDY_hart0_put_other_req_put(),
	    .RDY_hart0_gpr_mem_server_request_put(cpu$RDY_hart0_gpr_mem_server_request_put),
	    .hart0_gpr_mem_server_response_get(cpu$hart0_gpr_mem_server_response_get),
	    .RDY_hart0_gpr_mem_server_response_get(cpu$RDY_hart0_gpr_mem_server_response_get),
	    .RDY_hart0_csr_mem_server_request_put(cpu$RDY_hart0_csr_mem_server_request_put),
	    .hart0_csr_mem_server_response_get(cpu$hart0_csr_mem_server_response_get),
	    .RDY_hart0_csr_mem_server_response_get(cpu$RDY_hart0_csr_mem_server_response_get));

  // submodule debug_module
  mkDebug_Module debug_module(.CLK(CLK),
			      .RST_N(RST_N),
			      .dmi_read_addr_dm_addr(debug_module$dmi_read_addr_dm_addr),
			      .dmi_write_dm_addr(debug_module$dmi_write_dm_addr),
			      .dmi_write_dm_word(debug_module$dmi_write_dm_word),
			      .hart0_client_run_halt_response_put(debug_module$hart0_client_run_halt_response_put),
			      .hart0_csr_mem_client_response_put(debug_module$hart0_csr_mem_client_response_put),
			      .hart0_gpr_mem_client_response_put(debug_module$hart0_gpr_mem_client_response_put),
			      .master_arready(debug_module$master_arready),
			      .master_awready(debug_module$master_awready),
			      .master_bresp(debug_module$master_bresp),
			      .master_bvalid(debug_module$master_bvalid),
			      .master_rdata(debug_module$master_rdata),
			      .master_rresp(debug_module$master_rresp),
			      .master_rvalid(debug_module$master_rvalid),
			      .master_wready(debug_module$master_wready),
			      .EN_dmi_read_addr(debug_module$EN_dmi_read_addr),
			      .EN_dmi_read_data(debug_module$EN_dmi_read_data),
			      .EN_dmi_write(debug_module$EN_dmi_write),
			      .EN_hart0_get_reset_req_get(debug_module$EN_hart0_get_reset_req_get),
			      .EN_hart0_client_run_halt_request_get(debug_module$EN_hart0_client_run_halt_request_get),
			      .EN_hart0_client_run_halt_response_put(debug_module$EN_hart0_client_run_halt_response_put),
			      .EN_hart0_get_other_req_get(debug_module$EN_hart0_get_other_req_get),
			      .EN_hart0_gpr_mem_client_request_get(debug_module$EN_hart0_gpr_mem_client_request_get),
			      .EN_hart0_gpr_mem_client_response_put(debug_module$EN_hart0_gpr_mem_client_response_put),
			      .EN_hart0_csr_mem_client_request_get(debug_module$EN_hart0_csr_mem_client_request_get),
			      .EN_hart0_csr_mem_client_response_put(debug_module$EN_hart0_csr_mem_client_response_put),
			      .EN_get_ndm_reset_req_get(debug_module$EN_get_ndm_reset_req_get),
			      .RDY_dmi_read_addr(debug_module$RDY_dmi_read_addr),
			      .dmi_read_data(debug_module$dmi_read_data),
			      .RDY_dmi_read_data(debug_module$RDY_dmi_read_data),
			      .RDY_dmi_write(debug_module$RDY_dmi_write),
			      .RDY_hart0_get_reset_req_get(debug_module$RDY_hart0_get_reset_req_get),
			      .hart0_client_run_halt_request_get(debug_module$hart0_client_run_halt_request_get),
			      .RDY_hart0_client_run_halt_request_get(debug_module$RDY_hart0_client_run_halt_request_get),
			      .RDY_hart0_client_run_halt_response_put(debug_module$RDY_hart0_client_run_halt_response_put),
			      .hart0_get_other_req_get(debug_module$hart0_get_other_req_get),
			      .RDY_hart0_get_other_req_get(debug_module$RDY_hart0_get_other_req_get),
			      .hart0_gpr_mem_client_request_get(debug_module$hart0_gpr_mem_client_request_get),
			      .RDY_hart0_gpr_mem_client_request_get(debug_module$RDY_hart0_gpr_mem_client_request_get),
			      .RDY_hart0_gpr_mem_client_response_put(debug_module$RDY_hart0_gpr_mem_client_response_put),
			      .hart0_csr_mem_client_request_get(debug_module$hart0_csr_mem_client_request_get),
			      .RDY_hart0_csr_mem_client_request_get(debug_module$RDY_hart0_csr_mem_client_request_get),
			      .RDY_hart0_csr_mem_client_response_put(debug_module$RDY_hart0_csr_mem_client_response_put),
			      .RDY_get_ndm_reset_req_get(debug_module$RDY_get_ndm_reset_req_get),
			      .master_awvalid(debug_module$master_awvalid),
			      .master_awaddr(debug_module$master_awaddr),
			      .master_awprot(debug_module$master_awprot),
			      .master_wvalid(debug_module$master_wvalid),
			      .master_wdata(debug_module$master_wdata),
			      .master_wstrb(debug_module$master_wstrb),
			      .master_bready(debug_module$master_bready),
			      .master_arvalid(debug_module$master_arvalid),
			      .master_araddr(debug_module$master_araddr),
			      .master_arprot(debug_module$master_arprot),
			      .master_rready(debug_module$master_rready));

  // submodule f_reset_reqs
  FIFO20 #(.guarded(32'd1)) f_reset_reqs(.RST(RST_N),
					 .CLK(CLK),
					 .ENQ(f_reset_reqs$ENQ),
					 .DEQ(f_reset_reqs$DEQ),
					 .CLR(f_reset_reqs$CLR),
					 .FULL_N(f_reset_reqs$FULL_N),
					 .EMPTY_N(f_reset_reqs$EMPTY_N));

  // submodule f_reset_requestor
  FIFO2 #(.width(32'd1), .guarded(32'd1)) f_reset_requestor(.RST(RST_N),
							    .CLK(CLK),
							    .D_IN(f_reset_requestor$D_IN),
							    .ENQ(f_reset_requestor$ENQ),
							    .DEQ(f_reset_requestor$DEQ),
							    .CLR(f_reset_requestor$CLR),
							    .D_OUT(f_reset_requestor$D_OUT),
							    .FULL_N(f_reset_requestor$FULL_N),
							    .EMPTY_N(f_reset_requestor$EMPTY_N));

  // submodule f_reset_rsps
  FIFO20 #(.guarded(32'd1)) f_reset_rsps(.RST(RST_N),
					 .CLK(CLK),
					 .ENQ(f_reset_rsps$ENQ),
					 .DEQ(f_reset_rsps$DEQ),
					 .CLR(f_reset_rsps$CLR),
					 .FULL_N(f_reset_rsps$FULL_N),
					 .EMPTY_N(f_reset_rsps$EMPTY_N));

  // rule RL_rl_cpu_hart0_reset_from_soc_start
  assign CAN_FIRE_RL_rl_cpu_hart0_reset_from_soc_start =
	     cpu$RDY_hart0_server_reset_request_put && f_reset_reqs$EMPTY_N &&
	     f_reset_requestor$FULL_N ;
  assign WILL_FIRE_RL_rl_cpu_hart0_reset_from_soc_start =
	     CAN_FIRE_RL_rl_cpu_hart0_reset_from_soc_start ;

  // rule RL_rl_cpu_hart0_reset_from_dm_start
  assign CAN_FIRE_RL_rl_cpu_hart0_reset_from_dm_start =
	     debug_module$RDY_hart0_get_reset_req_get &&
	     cpu$RDY_hart0_server_reset_request_put &&
	     f_reset_requestor$FULL_N ;
  assign WILL_FIRE_RL_rl_cpu_hart0_reset_from_dm_start =
	     CAN_FIRE_RL_rl_cpu_hart0_reset_from_dm_start &&
	     !WILL_FIRE_RL_rl_cpu_hart0_reset_from_soc_start ;

  // rule RL_rl_cpu_hart0_reset_complete
  assign CAN_FIRE_RL_rl_cpu_hart0_reset_complete =
	     cpu$RDY_hart0_server_reset_response_get &&
	     f_reset_requestor$EMPTY_N &&
	     (!f_reset_requestor$D_OUT || f_reset_rsps$FULL_N) ;
  assign WILL_FIRE_RL_rl_cpu_hart0_reset_complete =
	     CAN_FIRE_RL_rl_cpu_hart0_reset_complete ;

  // rule RL_ClientServerRequest
  assign CAN_FIRE_RL_ClientServerRequest =
	     debug_module$RDY_hart0_client_run_halt_request_get &&
	     cpu$RDY_hart0_server_run_halt_request_put ;
  assign WILL_FIRE_RL_ClientServerRequest = CAN_FIRE_RL_ClientServerRequest ;

  // rule RL_ClientServerResponse
  assign CAN_FIRE_RL_ClientServerResponse =
	     debug_module$RDY_hart0_client_run_halt_response_put &&
	     cpu$RDY_hart0_server_run_halt_response_get ;
  assign WILL_FIRE_RL_ClientServerResponse =
	     CAN_FIRE_RL_ClientServerResponse ;

  // rule RL_mkConnectionGetPut
  assign CAN_FIRE_RL_mkConnectionGetPut =
	     debug_module$RDY_hart0_get_other_req_get ;
  assign WILL_FIRE_RL_mkConnectionGetPut =
	     debug_module$RDY_hart0_get_other_req_get ;

  // rule RL_ClientServerRequest_1
  assign CAN_FIRE_RL_ClientServerRequest_1 =
	     debug_module$RDY_hart0_gpr_mem_client_request_get &&
	     cpu$RDY_hart0_gpr_mem_server_request_put ;
  assign WILL_FIRE_RL_ClientServerRequest_1 =
	     CAN_FIRE_RL_ClientServerRequest_1 ;

  // rule RL_ClientServerResponse_1
  assign CAN_FIRE_RL_ClientServerResponse_1 =
	     debug_module$RDY_hart0_gpr_mem_client_response_put &&
	     cpu$RDY_hart0_gpr_mem_server_response_get ;
  assign WILL_FIRE_RL_ClientServerResponse_1 =
	     CAN_FIRE_RL_ClientServerResponse_1 ;

  // rule RL_ClientServerRequest_2
  assign CAN_FIRE_RL_ClientServerRequest_2 =
	     debug_module$RDY_hart0_csr_mem_client_request_get &&
	     cpu$RDY_hart0_csr_mem_server_request_put ;
  assign WILL_FIRE_RL_ClientServerRequest_2 =
	     CAN_FIRE_RL_ClientServerRequest_2 ;

  // rule RL_ClientServerResponse_2
  assign CAN_FIRE_RL_ClientServerResponse_2 =
	     debug_module$RDY_hart0_csr_mem_client_response_put &&
	     cpu$RDY_hart0_csr_mem_server_response_get ;
  assign WILL_FIRE_RL_ClientServerResponse_2 =
	     CAN_FIRE_RL_ClientServerResponse_2 ;

  // submodule cpu
  assign cpu$dmem_master_arready = cpu_dmem_master_arready ;
  assign cpu$dmem_master_awready = cpu_dmem_master_awready ;
  assign cpu$dmem_master_bresp = cpu_dmem_master_bresp ;
  assign cpu$dmem_master_bvalid = cpu_dmem_master_bvalid ;
  assign cpu$dmem_master_rdata = cpu_dmem_master_rdata ;
  assign cpu$dmem_master_rresp = cpu_dmem_master_rresp ;
  assign cpu$dmem_master_rvalid = cpu_dmem_master_rvalid ;
  assign cpu$dmem_master_wready = cpu_dmem_master_wready ;
  assign cpu$external_interrupt_req_set_not_clear =
	     cpu_external_interrupt_req_set_not_clear ;
  assign cpu$hart0_csr_mem_server_request_put =
	     debug_module$hart0_csr_mem_client_request_get ;
  assign cpu$hart0_gpr_mem_server_request_put =
	     debug_module$hart0_gpr_mem_client_request_get ;
  assign cpu$hart0_put_other_req_put = debug_module$hart0_get_other_req_get ;
  assign cpu$hart0_server_run_halt_request_put =
	     debug_module$hart0_client_run_halt_request_get ;
  assign cpu$imem_master_arready = cpu_imem_master_arready ;
  assign cpu$imem_master_awready = cpu_imem_master_awready ;
  assign cpu$imem_master_bresp = cpu_imem_master_bresp ;
  assign cpu$imem_master_bvalid = cpu_imem_master_bvalid ;
  assign cpu$imem_master_rdata = cpu_imem_master_rdata ;
  assign cpu$imem_master_rresp = cpu_imem_master_rresp ;
  assign cpu$imem_master_rvalid = cpu_imem_master_rvalid ;
  assign cpu$imem_master_wready = cpu_imem_master_wready ;
  assign cpu$near_mem_slave_araddr = cpu_slave_araddr ;
  assign cpu$near_mem_slave_arprot = cpu_slave_arprot ;
  assign cpu$near_mem_slave_arvalid = cpu_slave_arvalid ;
  assign cpu$near_mem_slave_awaddr = cpu_slave_awaddr ;
  assign cpu$near_mem_slave_awprot = cpu_slave_awprot ;
  assign cpu$near_mem_slave_awvalid = cpu_slave_awvalid ;
  assign cpu$near_mem_slave_bready = cpu_slave_bready ;
  assign cpu$near_mem_slave_rready = cpu_slave_rready ;
  assign cpu$near_mem_slave_wdata = cpu_slave_wdata ;
  assign cpu$near_mem_slave_wstrb = cpu_slave_wstrb ;
  assign cpu$near_mem_slave_wvalid = cpu_slave_wvalid ;
  assign cpu$set_verbosity_logdelay = set_verbosity_logdelay ;
  assign cpu$set_verbosity_verbosity = set_verbosity_verbosity ;
  assign cpu$EN_hart0_server_reset_request_put =
	     WILL_FIRE_RL_rl_cpu_hart0_reset_from_dm_start ||
	     WILL_FIRE_RL_rl_cpu_hart0_reset_from_soc_start ;
  assign cpu$EN_hart0_server_reset_response_get =
	     CAN_FIRE_RL_rl_cpu_hart0_reset_complete ;
  assign cpu$EN_set_verbosity = EN_set_verbosity ;
  assign cpu$EN_hart0_server_run_halt_request_put =
	     CAN_FIRE_RL_ClientServerRequest ;
  assign cpu$EN_hart0_server_run_halt_response_get =
	     CAN_FIRE_RL_ClientServerResponse ;
  assign cpu$EN_hart0_put_other_req_put =
	     debug_module$RDY_hart0_get_other_req_get ;
  assign cpu$EN_hart0_gpr_mem_server_request_put =
	     CAN_FIRE_RL_ClientServerRequest_1 ;
  assign cpu$EN_hart0_gpr_mem_server_response_get =
	     CAN_FIRE_RL_ClientServerResponse_1 ;
  assign cpu$EN_hart0_csr_mem_server_request_put =
	     CAN_FIRE_RL_ClientServerRequest_2 ;
  assign cpu$EN_hart0_csr_mem_server_response_get =
	     CAN_FIRE_RL_ClientServerResponse_2 ;

  // submodule debug_module
  assign debug_module$dmi_read_addr_dm_addr = dm_dmi_read_addr_dm_addr ;
  assign debug_module$dmi_write_dm_addr = dm_dmi_write_dm_addr ;
  assign debug_module$dmi_write_dm_word = dm_dmi_write_dm_word ;
  assign debug_module$hart0_client_run_halt_response_put =
	     cpu$hart0_server_run_halt_response_get ;
  assign debug_module$hart0_csr_mem_client_response_put =
	     cpu$hart0_csr_mem_server_response_get ;
  assign debug_module$hart0_gpr_mem_client_response_put =
	     cpu$hart0_gpr_mem_server_response_get ;
  assign debug_module$master_arready = dm_master_arready ;
  assign debug_module$master_awready = dm_master_awready ;
  assign debug_module$master_bresp = dm_master_bresp ;
  assign debug_module$master_bvalid = dm_master_bvalid ;
  assign debug_module$master_rdata = dm_master_rdata ;
  assign debug_module$master_rresp = dm_master_rresp ;
  assign debug_module$master_rvalid = dm_master_rvalid ;
  assign debug_module$master_wready = dm_master_wready ;
  assign debug_module$EN_dmi_read_addr = EN_dm_dmi_read_addr ;
  assign debug_module$EN_dmi_read_data = EN_dm_dmi_read_data ;
  assign debug_module$EN_dmi_write = EN_dm_dmi_write ;
  assign debug_module$EN_hart0_get_reset_req_get =
	     WILL_FIRE_RL_rl_cpu_hart0_reset_from_dm_start ;
  assign debug_module$EN_hart0_client_run_halt_request_get =
	     CAN_FIRE_RL_ClientServerRequest ;
  assign debug_module$EN_hart0_client_run_halt_response_put =
	     CAN_FIRE_RL_ClientServerResponse ;
  assign debug_module$EN_hart0_get_other_req_get =
	     debug_module$RDY_hart0_get_other_req_get ;
  assign debug_module$EN_hart0_gpr_mem_client_request_get =
	     CAN_FIRE_RL_ClientServerRequest_1 ;
  assign debug_module$EN_hart0_gpr_mem_client_response_put =
	     CAN_FIRE_RL_ClientServerResponse_1 ;
  assign debug_module$EN_hart0_csr_mem_client_request_get =
	     CAN_FIRE_RL_ClientServerRequest_2 ;
  assign debug_module$EN_hart0_csr_mem_client_response_put =
	     CAN_FIRE_RL_ClientServerResponse_2 ;
  assign debug_module$EN_get_ndm_reset_req_get = EN_dm_ndm_reset_req_get_get ;

  // submodule f_reset_reqs
  assign f_reset_reqs$ENQ = EN_cpu_reset_server_request_put ;
  assign f_reset_reqs$DEQ =
	     cpu$RDY_hart0_server_reset_request_put && f_reset_reqs$EMPTY_N &&
	     f_reset_requestor$FULL_N ;
  assign f_reset_reqs$CLR = 1'b0 ;

  // submodule f_reset_requestor
  assign f_reset_requestor$D_IN =
	     !WILL_FIRE_RL_rl_cpu_hart0_reset_from_dm_start ;
  assign f_reset_requestor$ENQ =
	     WILL_FIRE_RL_rl_cpu_hart0_reset_from_dm_start ||
	     WILL_FIRE_RL_rl_cpu_hart0_reset_from_soc_start ;
  assign f_reset_requestor$DEQ = CAN_FIRE_RL_rl_cpu_hart0_reset_complete ;
  assign f_reset_requestor$CLR = 1'b0 ;

  // submodule f_reset_rsps
  assign f_reset_rsps$ENQ =
	     WILL_FIRE_RL_rl_cpu_hart0_reset_complete &&
	     f_reset_requestor$D_OUT ;
  assign f_reset_rsps$DEQ = EN_cpu_reset_server_response_get ;
  assign f_reset_rsps$CLR = 1'b0 ;
endmodule  // mkCore

